# Generated by Django 3.1.5 on 2021-01-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=128)),
                ('movie_title', models.CharField(max_length=128)),
                ('movie_year', models.CharField(max_length=128)),
                ('imbd_rating', models.FloatField()),
                ('number_of_imdb_votes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='add_data_to_db.Genre')),
            ],
        ),
    ]
